trigger:
- development 
pool:
  vmImage: 'ubuntu-latest'
steps:

- task: Maven@3
  displayName: 'MavenFase'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test package'
    #options: '-X'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'SpringLabTest'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
- task: PublishBuildArtifacts@1
  displayName: 'PublishBuildArtifacts'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
    ArtifactName: 'PublishedProject'
    publishLocation: 'Container'